leoaginna/BOATS_AIRBNB

Gemfile, Gemfile.lock, app/controllers/boats_controller.rb, app/controllers/rentals_controller.rb, app/models/boat.rb, app/models/rental.rb, app/models/user.rb, app/views/rentals/edit.html.erb, app/views/rentals/new.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20240311185051_create_boats.rb, db/migrate/20240311185753_devise_create_users.rb, db/migrate/20240311190009_create_rentals.rb, db/schema.rb, test/controllers/boats_controller_test.rb, test/controllers/rentals_controller_test.rb, test/models/boat_test.rb, test/models/rental_test.rb, test/models/user_test.rb
created setup for models, controllers and routes
=> Initial setup

app/controllers/boats_controller.rb, app/controllers/rentals_controller.rb
Added rentals and boats controllers actions. Notice there's no new (!) action as it will be embedded on the boat show
=> Added controller actions

app/controllers/boats_controller.rb, db/migrate/20240312151756_add_available_from_to_boats.rb, db/migrate/20240312152546_add_available_until_to_boats.rb, db/schema.rb
added available_to and available_from to boats table as well as boat_params
=> Add available dates

app/views/boats/index.html.erb, app/views/pages/home.html.erb
=> added home page view (index)

db/migrate/20240312171041_add_boat_user_reference_to_boats.rb
=> added boat user to DB

app/views/boats/new.html.erb
=> added form for new boat

config/routes.rb
=> fixin typo in routes

app/controllers/rentals_controller.rb, app/views/rentals/index.html.erb
my rentals code & rental index def updated
=> My rentals

app/views/boats/show.html.erb, config/routes.rb
- put boat show back button at top
- fixed book button path
=> Boat show fixes

app/controllers/application_controller.rb, app/controllers/boats_controller.rb, app/views/boats/my_boats.html.erb, app/views/boats/new.html.erb, app/views/boats/show.html.erb, app/views/layouts/application.html.erb, app/views/rentals/index.html.erb, app/views/shared/_flashes.html.erb, db/migrate/20240312224458_add_name_to_users.rb, db/schema.rb
-added _flashes in the shared file
- added the flashes in the application.html
- Application controller:
before_action :authenticate_user!
def configure_permitted_parameters
devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
=> Before actions user

app/controllers/boats_controller.rb, app/views/boats/my_boats.html.erb
i change the redirection path -after edit boat- to my boats, (now is back to my boats),  this ations was made by cahnging de function def update of the boats controller, and i also changed the name of the buttons in my boats
=> button edit in my boats redirect back to my boats

app/controllers/boats_controller.rb, app/controllers/rentals_controller.rb, app/views/boats/show.html.erb, app/views/rentals/index.html.erb
Fixed typos such as using end_date instead of end_time for rentals and trying to access rental.price instead of rental.boat.price
refactor needed !
=> Myrentals fixes

app/views/boats/index.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
Added cards and simple style, added shadow to navbar too
=> added caard simple styles and added a shadow to the navbar and cards

app/views/rentals/index.html.erb
syntax error in myrentals corrected
=> fixed myrentals syntax error

.gitignore, Gemfile, Gemfile.lock, app/controllers/boats_controller.rb, app/views/boats/_form.html.erb, app/views/boats/index.html.erb, app/views/boats/my_boats.html.erb, app/views/boats/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20240313143641_create_active_storage_tables.active_storage.rb, db/schema.rb
-added cloudinary:
-env
- configuration, 
- index, show and my boats display pics, 
- controller strong params
=> Cloudinary

app/views/shared/_navbar.html.erb
=> log out now working

Gemfile, Gemfile.lock, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
added links and fix some button needs work
=> added links and fix some button

app/views/shared/_navbar.html.erb
=> added some links to dropdown

app/controllers/boats_controller.rb, app/views/rentals/index.html.erb
- boats/new now redirects to myboats when booking
- images now visible in rentals
=> Minor fixes

app/views/shared/_navbar.html.erb
added conditional to dropdown; when sign in and when sign out
=> added conditionals to dropdown

app/views/boats/index.html.erb
we had problems with responsiveness of the cards, fixed it. now they're responsive for diferent screen sizes
=> fixed responsiveness of cards for different sizes

app/views/boats/_form.html.erb, app/views/rentals/index.html.erb
changed the name of the button in for creating a boat, and changed a name in my boats
=> update buttons name in create new boat

app/views/boats/index.html.erb
added a carousell with bootstrap, fixed the response of the card and borders are rounded everything works nice
=> fixed the cards and added carousel

app/controllers/boats_controller.rb, app/views/boats/_form.html.erb
used controller logic and label conditionals to not replace photos when none are passed
=> photos are now saved on edit

app/views/boats/new.html.erb
added style to the form in new boat!
=> style form: new boat

app/views/boats/index.html.erb
- index: added logic, if current user is the owner, button is show my boat and redirect to myboats
=> fixed, in index, if owner, show your boat, not book

app/controllers/rentals_controller.rb, app/views/boats/show.html.erb, app/views/rentals/index.html.erb
- rental controller: cannot book in the past
- - rental controller: cannot book end date after start date
-
=> now cannot book in the past, or end date after start date

app/views/rentals/index.html.erb
new lines in rentals:
added a variable total days, with that now we display the total price for past and current rentals
=> added total to rentals

app/views/boats/my_boats.html.erb, app/views/boats/show.html.erb
- myboats view: button on the top
- rentals: a boat owner cannot book its own boat
=> fix button top in myboats. the user cannot book its own boats

app/views/boats/edit.html.erb
edit form has now the same style of the new form.
=> edit form has now the same style of the new form

app/views/rentals/index.html.erb
added the canceled text when cancelling rentals, rentals views
=> added the canceled text when cancelling rentals

app/views/layouts/application.html.erb
=> footer in home page are now visible, thanks to a link in the head of the html

app/controllers/boats_controller.rb, app/views/boats/show.html.erb, config/routes.rb
- addded suspend action in the boats controller
- refactored controller
- added route for suspend button
- suspended boats are not visible in the platform
=> Suspend button

app/views/boats/_form.html.erb
=> dates on new boat

app/controllers/rentals_controller.rb, app/views/boats/_rental-form.html.erb, app/views/boats/edit.html.erb, app/views/boats/show.html.erb, app/views/rentals/edit.html.erb, app/views/rentals/index.html.erb, config/routes.rb
- Edit button works
- created an rentals-edit view 
- created an edit method and updated the update method in rentals controller
=> edit button works

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
-changed main colors and boat card button styling 
-changed nav design
=> A few general style changes

app/controllers/application_controller.rb
=> sign up path is fixed now

app/assets/stylesheets/config/_colors.scss, app/controllers/application_controller.rb, app/views/boats/_form.html.erb, app/views/boats/new.html.erb
the create btn at new boat now looks good, also changed color for btns
=> create btn now looks good

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_variables.scss, app/views/boats/_card.html.erb, app/views/boats/index.html.erb
map sticks on desktop. sits at bottom on mobile
=> map sticks

Gemfile, Gemfile.lock, app/controllers/boats_controller.rb, app/models/application_record.rb, app/models/boat.rb, app/views/shared/_navbar.html.erb
search bar works with pg-search
=> Search bar

app/views/boats/show.html.erb
made visible the email of the user renting a boat, in the show of my boats
=> Info my boats

app/views/layouts/application.html.erb
look the name of the page (tab) in the browser, there you find a boat now
=> added logo to the favicon: name of the tab in the browser
